#!/bin/bash
set -euo pipefail

docker build -t bjoern .
docker run -it --rm \
    --cap-add=SYS_PTRACE \
    --security-opt seccomp=unconfined \
    -v $(pwd):/bjoern -v ~/.pypirc:/root/.pypirc \
    -w /bjoern \
    -p 8080:8080 \
    bjoern bash

